// PairTerminal — first-screen on a fresh tablet. Cashier types the
// 6-digit pairing code generated by an admin (Terminals page in admin).
// On success, the device record is stored in localStorage and survives
// staff sign-out / sign-in. "Switch terminal" in the user menu clears it
// for re-pairing.

import React, { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { usePairDeviceMutation } from "../features/pos/posApi";
import { setTerminal } from "../lib/terminal";

const APP_VERSION = "0.1.0";

export default function PairTerminal({ onPaired }) {
  const [code, setCode] = useState("");
  const [pair, { isLoading }] = usePairDeviceMutation();
  const inputRef = useRef(null);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const submit = async (e) => {
    e?.preventDefault?.();
    if (code.length < 6) {
      toast.error("Pairing code must be 6 digits");
      return;
    }
    try {
      const res = await pair({ code, appVersion: APP_VERSION }).unwrap();
      const device = res?.data;
      if (!device?.deviceId) {
        toast.error("Pairing succeeded but no device data returned");
        return;
      }
      setTerminal({
        deviceId: device.deviceId,
        deviceName: device.deviceName,
        venueId: device.venueId,
        venueName: device.venueName,
        templateId: device.templateId,
        pairedAt: new Date().toISOString(),
      });
      toast.success(`Paired to ${device.deviceName}`);
      onPaired?.(device);
    } catch (err) {
      console.error("Pair error:", err);
      const msg =
        err?.data?.error ||
        err?.data?.message ||
        (err?.status === 404 && "Invalid pairing code") ||
        (err?.status === 410 && "Pairing code has expired — ask admin to regenerate") ||
        (err?.status === "FETCH_ERROR" && "Can't reach the API. Check VITE_API_BASE_URL in .env.") ||
        (typeof err?.status === "number" && `HTTP ${err.status}`) ||
        "Pairing failed";
      toast.error(String(msg), { duration: 6000 });
    }
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "var(--ink-25)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: 20,
      }}
    >
      <form
        onSubmit={submit}
        style={{
          background: "white",
          border: "2px solid var(--ink-800)",
          borderRadius: 18,
          padding: 32,
          boxShadow: "0 6px 0 var(--ink-800)",
          width: "min(440px, 100%)",
          textAlign: "center",
        }}
      >
        <div
          style={{
            width: 72, height: 72, borderRadius: 20,
            background: "var(--aero-orange-500)",
            border: "2px solid var(--ink-800)",
            color: "white",
            display: "inline-flex", alignItems: "center", justifyContent: "center",
            fontFamily: "var(--font-display)", fontSize: 34, fontWeight: 800,
            boxShadow: "0 6px 0 var(--aero-orange-700)",
            marginBottom: 16,
          }}
        >
          A
        </div>
        <div
          style={{
            fontFamily: "var(--font-display)",
            fontSize: 24,
            fontWeight: 800,
            color: "var(--ink-900)",
            marginBottom: 6,
          }}
        >
          Pair this terminal
        </div>
        <div style={{ fontSize: 13, color: "var(--ink-500)", marginBottom: 24 }}>
          Ask a manager to generate a pairing code from
          <br />
          <strong>Settings → Terminals</strong> in the admin app.
        </div>

        <input
          ref={inputRef}
          inputMode="numeric"
          pattern="[0-9]*"
          maxLength={6}
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
          placeholder="• • • • • •"
          autoComplete="off"
          style={{
            width: "100%",
            padding: "20px 14px",
            borderRadius: 14,
            border: "2px solid var(--ink-300)",
            background: "white",
            fontFamily: "var(--font-mono)",
            fontSize: 38,
            fontWeight: 800,
            color: "var(--ink-900)",
            textAlign: "center",
            letterSpacing: "0.5em",
            boxSizing: "border-box",
            marginBottom: 18,
          }}
        />

        <button
          type="submit"
          disabled={isLoading || code.length < 6}
          className="a-btn a-btn--primary"
          style={{ width: "100%", justifyContent: "center", padding: "14px 16px", fontSize: 16 }}
        >
          {isLoading ? "Pairing…" : "Pair terminal"}
        </button>

        <div
          style={{
            marginTop: 18,
            fontSize: 11,
            color: "var(--ink-400)",
            fontFamily: "var(--font-mono)",
          }}
        >
          App v{APP_VERSION}
        </div>
      </form>
    </div>
  );
}
